// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PH_Warehouse","status":true,"description":"This plugin allows the creation of warehouses where you can store items in the game.","parameters":{"---Options---":"","All Together":"0","Stack Item Quantity":"0","---Vocabulary---":"","Withdraw Text":"取出","Deposit Text":"放入","All Text":"All","Available Space Text":"剩余空间："}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"-200","Offset Y":"0","Width":"180","Background":"2"}},
{"name":"YEP_BattleStatusWindow","status":true,"description":"v1.05 A simple battle status window that shows the\nfaces of your party members in horizontal format.","parameters":{"---Visual---":"","No Action Icon":"16","Name Font Size":"20","Param Font Size":"20","Param Y Buffer":"7","Param Current Max":"true","Adjust Columns":"true","---Actor Switching---":"","Left / Right":"true","PageUp / PageDown":"true","Allow Turn Skip":"true","---Front View---":"","Show Animations":"true","Show Sprites":"true","Align Animations":"true","X Offset":"50","Y Offset":"-16"}}
];
