// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PH_Warehouse","status":true,"description":"This plugin allows the creation of warehouses where you can store items in the game.","parameters":{"---Options---":"","All Together":"0","Stack Item Quantity":"0","---Vocabulary---":"","Withdraw Text":"放入","Deposit Text":"取出","All Text":"All","Available Space Text":"剩余空间："}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}}
];
